services:
  es-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    platform: linux/amd64
    container_name: es-node1
    environment:
      - node.name=es-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node2,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  es-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    platform: linux/amd64
    container_name: es-node2
    environment:
      - node.name=es-node2
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data2:/usr/share/elasticsearch/data
    ports:
      - 9301:9300

  es-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    platform: linux/amd64
    container_name: es-node3
    environment:
      - node.name=es-node3
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data3:/usr/share/elasticsearch/data
    ports:
      - 9302:9300

volumes:
  es-data1:
    driver: local
  es-data2:
    driver: local
  es-data3:
    driver: local
