version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: python --version > python_version
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "./search_gov_crawler/requirements.txt" }}-{{ checksum "python_version"}}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r ./search_gov_crawler/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: deps-{{ .Branch }}-{{ checksum "./search_gov_crawler/requirements.txt" }}-{{ checksum "python_version"}}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest tests --ignore=tests/integration_tests/

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
